print('Welcome to my _____(adj) Mad Libs \nPlease enter the following information for a (wacky) story')
name = input("Enter your name: ").title()
name2 = input("Enter another name: ").title()
name3 = input("Enter another name: ").title()
verb1 = input("Enter a verb: ")
adj1 = input("Enter an adjective: ")
noun1 = input("Enter a noun: ")
noun2 = input("Enter another noun: ")
verb2 = input("Enter a past tense verb: ")
adj2 = input("Enter another adjective: ")
print('One day, ' + str(name) + ' was out for a(n) ' + str(adj1) + ' ' + str(verb1) + '.')
print('Suddenly a(n) ' + str(noun1)+' and a(n) ' + str(noun2) + ' ' + str(verb2) + ' out of nowhere.')
print('The ' + str(noun1) + '\'s name was ' + str(name2) + ' and the ' + str(noun2) + '\'s name was ' + str(name3))
print('The sum of the number of characters in their name is ' + str(int(len(name2)) + int(len(name3))))
#python documentation for strings
print('They both told ' + str(name) + ' to have a ' + str(adj2) + ' day!')