import turtle
alex = turtle.Turtle()
wn = turtle.Screen()
wn.bgcolor("white")
alex.color("green")
alex.pensize(3)
alex.penup()
alex.back(100)
alex.left(90)
alex.forward(100)
alex.right(90)
alex.pendown()
for i in range(3):
    alex.forward(50)
    alex.left(120)
alex.penup()
alex.forward(200)
alex.pendown()
for i in range(4):
    alex.forward(50)
    alex.left(90)
alex.penup()
alex.right(90)
alex.forward(200)
alex.left(90)
alex.pendown()
for i in range(6):
    alex.forward(50)
    alex.left(60)
alex.penup()
alex.right(180)
alex.forward(200)
alex.right(180)
alex.pendown()
for i in range(8):
    alex.forward(50)
    alex.left(45)

wn.exitonclick()
